package:
  name: rockverse
  version: 0.0.0

  #"{{ environ['GIT_DESCRIBE_TAG'] }}"

source:
  path: .

build:
  noarch: python  # Indicating it's a Python package, not platform-specific

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - colorama
    - cython
    - ipython[all]
    - ipywidgets
    - jupyterlab
    - matplotlib
    - nbsphinx
    - numba
    - numpy
    - pandas
    - pip
    - pydata-sphinx-theme
    - scipy==1.13
    - seaborn
    - sphinx
    - sphinx-design
    - spyder
    - sympy
    - tqdm
    - zarr[jupyter]>=2.18

about:
  home: "https://example.com"
  license: MIT