
name: Build and upload conda packages

on: [push]
#  push:
#    tags:
#      - "v*"  # This will trigger on tags like v0.1.0, v1.0.0, etc.

jobs:
  build:
    name: Build and Publish Conda Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'  # Use appropriate Python version

      - name: Install Miniconda
        uses: goanpeca/conda-action@v2
        with:
          miniconda-version: 'latest'

      - name: Create Conda environment
        run: |
          conda create --name myenv python=3.8
          conda activate myenv
          conda install conda-build anaconda-client  # Install necessary tools

      - name: Build the Conda Package
        run: |
          conda build .  # Assuming you're in the directory containing meta.yaml

      - name: Upload to Anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}  # Store token in GitHub secrets
        run: |
          conda activate myenv
          anaconda login --token $ANACONDA_TOKEN
          anaconda upload --force /path/to/package.tar.bz2  # Replace with your built package path
