
name: Build and upload conda packages

on: [push]
#  push:
#    tags:
#      - "v*"  # This will trigger on tags like v0.1.0, v1.0.0, etc.

jobs:
  build:
    name: Build and Publish Conda Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"  # Automatically installs the latest Miniconda version
          python-version: "3.8"  # Specify Python version for the environment
          auto-update-conda: true  # This will update conda to the latest version if needed

      - name: Install dependencies
        run: |
          conda install conda-build anaconda-client  # Install conda-build and anaconda-client
          conda init
          conda create --name myenv python=3.8  # Create environment with specified Python version
          conda activate myenv
          conda build .  # This assumes meta.yaml is in the root of your repo
          PACKAGE_PATH=$(conda build . --output)  # Capture the build output path
          echo "Built package at: $PACKAGE_PATH"

      - name: Create Conda environment and install package
        run: |
          conda init
          conda create --name myenv python=3.8  # Create environment with specified Python version
          conda activate myenv
          conda build .  # This assumes meta.yaml is in the root of your repo
          PACKAGE_PATH=$(conda build . --output)  # Capture the build output path
          echo "Built package at $PACKAGE_PATH"

      - name: Upload to Anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}  # Store your Anaconda API token in GitHub Secrets
        run: |
          conda activate myenv
          anaconda login --token $ANACONDA_API_TOKEN
          anaconda upload --force $PACKAGE_PATH  # Use the captured path